// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.download.attempts", 0);
user_pref("app.update.elevate.attempts", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1701844863);
user_pref("app.update.lastUpdateTime.background-update-timer", 1701845103);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1701844983);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1700115349);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1701845223);
user_pref("app.update.postupdate", true);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.dom.window.dump.enabled", false);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.lastAppBuildId", "20231102180027");
user_pref("extensions.lastAppVersion", "6.0.30");
user_pref("extensions.lastPlatformVersion", "60.9.0");
user_pref("extensions.notero.collectionSyncConfigs", "{\"2\":{\"syncEnabled\":true},\"4\":{\"syncEnabled\":true},\"5\":{\"syncEnabled\":true},\"6\":{\"syncEnabled\":true},\"7\":{\"syncEnabled\":true}}");
user_pref("extensions.notero.notionDatabaseID", "474b90301c0f471c9b6859399f6fa70b");
user_pref("extensions.notero.notionToken", "secret_G77WZ3xTO9jQzttbBcyf3i7iDks58rXBrRXYgDCJdck");
user_pref("extensions.notero.syncNotes", true);
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.zotero.automaticTags", false);
user_pref("extensions.zotero.dataDir", "/Users/zhenghang/Zotero");
user_pref("extensions.zotero.fileHandler.pdf", "system");
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.lastViewedFolder", "C5");
user_pref("extensions.zotero.lastWebDAVOrphanPurge", 1699925493);
user_pref("extensions.zotero.pane.persist", "{\"zotero-reader-sidebar-pane\":{\"collapsed\":\"true\"},\"zotero-collections-pane\":{\"width\":\"189\"},\"zotero-tags-splitter\":{},\"zotero-tag-selector-container\":{},\"zotero-collections-splitter\":{},\"zotero-layout-switcher\":{\"orient\":\"horizontal\"},\"zotero-items-pane\":{\"width\":\"410\"},\"zotero-items-splitter\":{\"orient\":\"horizontal\"},\"zotero-item-pane\":{\"width\":\"338\",\"height\":\"300\"},\"zotero-context-splitter\":{\"state\":\"collapsed\"},\"zotero-context-pane\":{},\"zotero-context-splitter-stacked\":{\"state\":\"collapsed\"},\"zotero-context-pane-inner\":{}}");
user_pref("extensions.zotero.prefVersion", 6);
user_pref("extensions.zotero.purge.tags", true);
user_pref("extensions.zotero.recentSaveTargets", "[{\"id\":\"C5\",\"sessionID\":\"oUxpqRDh\"}]");
user_pref("extensions.zotero.sourceList.persist", "{\"L1\":true,\"P1\":false,\"C2\":true}");
user_pref("extensions.zotero.sync.autoSync", false);
user_pref("extensions.zotero.sync.reminder.autoSync.enabled", false);
user_pref("extensions.zotero.sync.reminder.autoSync.lastDisplayed", 1699704415);
user_pref("extensions.zotero.sync.server.username", "zhenghang707@gmail.com");
user_pref("extensions.zotero.sync.storage.protocol", "webdav");
user_pref("extensions.zotero.sync.storage.url", "dav.jianguoyun.com/dav");
user_pref("extensions.zotero.sync.storage.username", "zhenghang707@gmail.com");
user_pref("extensions.zoteroMacWordIntegration.installed", true);
user_pref("extensions.zoteroMacWordIntegration.version", "6.0.10.SA.6.0.29");
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1700013420);
user_pref("intl.accept_languages", "en-US, en");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("places.database.lastMaintenance", 1700013420);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1697598412);
